version: '3'
services:
  app:
    platform: linux/amd64
    build:
      context: .
      target: dev
    command: uvicorn --host 0.0.0.0 --port 8000 app.main:app --reload
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    volumes:
      - ./:/workspace
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
