version: "3"
services:
  test-db:
    image: postgres:15.2-alpine
    ports:
      - 5433:5432
    volumes:
      - test-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=loden
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
volumes:
  test-db-volume:
