version: '3'
services:
  backend:
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./app:/workspace/app
    build:
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=loden
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

volumes:
  db-volume:
