version: '3'
services:
  db:
    image: postgres:15.2-alpine
    command: -c log_statement=all
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    volumes:
      - db-volume:/var/lib/postgresql/data

  auth-redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379

  test-db:
    image: postgres:15.2-alpine
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5433:5432
    environment:
      POSTGRES_SERVER: test-db
      POSTGRES_DB: sessionaway
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

volumes:
  db-volume:
